package:
  name: mcvine-full
  version: "1.3.1a9"

requirements:
  run:
    - mcvine 1.3.1a9
    - mcvine.instruments
    - mcvine.workflow
    - mcvine.phonon
    - mantid-framework 3.10

build:

about:
  home: 
  license: 
  license_file:
