package:
  name: danse.ins.dsm
  version: "0.1.2"

source:
  git_rev: v0.1.2
  git_url: https://github.com/danse-inelastic/dsm.git

requirements:
  build:
    - cmake

  host:
    - python
    - danse.ins

  run:
    - python
    - danse.ins

build:
  noarch: python
  script_env:

test:
  imports:
    - danse.ins.dsm
  

about:
  home: 
  license:
  license_file:
