package:
  name: danse.ins.dsm
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/danse-inelastic/dsm.git

requirements:
  build:
    - danse.ins
    - cmake

  run:
    - danse.ins

test:
  imports:
    - danse.ins.dsm
  

about:
  home: 
  license:
  license_file:
