package:
  name: danse.ins.dsm
  version: "0.1.1unstable"

source:
  git_rev: master
  git_url: https://github.com/danse-inelastic/dsm.git

requirements:
  build:
    - python
    - danse.ins
    - cmake

  run:
    - python
    - danse.ins

build:
  script_env:

test:
  imports:
    - danse.ins.dsm
  

about:
  home: 
  license:
  license_file:
