package:
  name: journal
  version: "0.8.2"

source:
  git_rev: v0.8.2
  git_url: https://github.com/danse-inelastic/journal.git

requirements:
  build:
    - python
    - danse.ins
    - cmake

  run:
    - python
    - danse.ins

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - journal
  

about:
  home: 
  license:
  license_file:
