package:
  name: journal
  version: "0.8.4"

source:
  git_rev: v0.8.4
  git_url: https://github.com/danse-inelastic/journal.git

requirements:
  build:
    - {{ compiler('cxx') }}       7  # [linux]
    - cmake

  host:
    - python
    - danse.ins

  run:
    - python
    - danse.ins

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - journal
  

about:
  home: 
  license:
  license_file:
