package:
  name: journal
  version: "nightly"

source:
  git_rev: master
  git_url: https://github.com/danse-inelastic/journal.git

requirements:
  build:
    - python
    - danse.ins
    - cmake

  run:
    - python
    - danse.ins

test:
  imports:
    - journal
  

about:
  home: 
  license:
  license_file:
