package:
  name: danse.ins
  version: "0.1.1unstable"

source:
  git_rev: master
  git_url: https://github.com/danse-inelastic/danse.ins.git

requirements:
  build:
    - python
    - cmake

  run:
    - python

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - danse.ins
  

about:
  home: 
  license:
  license_file:
