package:
  name: danse.ins
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/danse-inelastic/danse.ins.git

requirements:
  build:
    - python
    - cmake

  run:
    - python

test:
  imports:
    - danse.ins
  

about:
  home: 
  license:
  license_file:
