package:
  name: mcvine.workflow
  version: "0.1.4"

source:
  git_rev: v0.1.4
  git_url: https://github.com/mcvine/workflow.git

requirements:
  build:
    - {{ compiler('cxx') }}    7                # [linux]
    - cmake
  host:
    - python

  run:
    - python
    - mcvine-core >=1.4.3
    - mcvine.instruments >=0.1.3

build:
  noarch: python

test:
  imports:
    - mcvine.workflow

about:
  home: 
  license:
  license_file:
