package:
  name: mcvine.workflow
  version: "0.1.0a2"

source:
  git_rev: v0.1.0a2
  git_url: https://github.com/mcvine/workflow.git

requirements:
  build:
    - python
    - cmake

  run:
    - python
    - numpy
    - mcvine

build:

test:
  imports:
    - mcvine.workflow

about:
  home: 
  license:
  license_file:
