package:
  name: danse.ins.matter
  version: "0.9.2"

source:
  git_rev: v0.9.2
  git_url: https://github.com/danse-inelastic/matter.git

requirements:
  build:
    - python
    - numpy
    - danse.ins
    - cmake

  run:
    - python
    - numpy
    - danse.ins

build:
  script_env:

test:
  imports:
    - danse.ins.matter
  

about:
  home: 
  license:
  license_file:
