package:
  name: danse.ins.matter
  version: "0.9.1unstable"

source:
  git_rev: master
  git_url: https://github.com/danse-inelastic/matter.git

requirements:
  build:
    - python
    - numpy x.x
    - danse.ins
    - cmake

  run:
    - python
    - numpy x.x
    - danse.ins

build:
  script_env:

test:
  imports:
    - danse.ins.matter
  

about:
  home: 
  license:
  license_file:
