package:
  name: danse.ins.matter
  version: "0.9.1unstable"

source:
  git_rev: master
  git_url: https://github.com/danse-inelastic/matter.git

requirements:
  build:
    - python
    - numpy
    - danse.ins
    - cmake

  run:
    - python
    - numpy
    - danse.ins

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - danse.ins.matter
  

about:
  home: 
  license:
  license_file:
