package:
  name: mcvine.acc
  version: "v0.1.0.rc1"
#  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_rev: v0.1.0_rc1
  git_url: https://github.com/mcvine/acc.git

requirements:
  host:
    - python
    - mcvine-core           >=1.4.7
    - numba                 ==0.53.1
    - h5py
    - versioningit

  run:
    - python
    - mcvine-core           >=1.4.7
    - numba                 ==0.53.1
    - h5py

build:
  noarch: python

test:
  requires:
    - pytest
  source_files:
    - .github/
    - tests/
  imports:
    - mcni
    - mcvine
    - mcvine.acc
  commands:
    - python .github/workflows/patch_numba.py
    - pytest tests/

about:
  home:
  license:
  license_file:
