python:
  - 3.10
gsl:
  - 2.7
boost:
  - 1.84
numpy:
  - 1
numpyext:
  - 0.1.4
bpext:
  - 0.1.5
histogram:
  - 0.4.2
pyre:
  - 0.8
structure:
  - 3.0.1  
pin_run_as_build:
  boost:
    max_pin: x.x
  gsl:
    max_pin: x.x
  numpy:
    max_pin: x
  numpyext:
    max_pin: x.x
  bpext:
    max_pin: x.x
  histogram:
    max_pin: x.x
  pyre:
    max_pin: x.x
