python:
  - 2.7
gsl:
  - 2.2
  - 2.4
  - 2.4
boost:
  - 1.66
  - 1.66
  - 1.69
numpy:
  - 1.13
  - 1.14
  - 1.16

zip_keys:
  - gsl
  - boost
  - numpy

pin_run_as_build:
  boost:
    max_pin: x.x
  gsl:
    max_pin: x.x
  numpy:
    max_pin: x.x
