python:
  - 3.10
gsl:
  - 2.7
boost:
  - 1.78
numpy:
  - 1.24.*
numpyext:
  - 0.1.3
bpext:
  - 0.1.4
histogram:
  - 0.4.2
pyre:
  - 0.8
  
pin_run_as_build:
  boost:
    max_pin: x.x
  gsl:
    max_pin: x.x
  numpy:
    max_pin: x.x
  numpyext:
    max_pin: x.x
  bpext:
    max_pin: x.x
  histogram:
    max_pin: x.x
  pyre:
    max_pin: x.x
