python:
  - 2.7
gsl:
#  - 2.2
  - 2.4
  - 2.4
boost:
#  - 1.66
  - 1.66
  - 1.69
numpy:
#  - 1.13.0
  - 1.14.0
  - 1.16.0
numpyext:
  - 0.1.2
bpext:
  - 0.1.3
histogram:
  - 0.3.5
drchops:
  - 2.0.2
  
zip_keys:
  - gsl
  - boost
  - numpy

pin_run_as_build:
  boost:
    max_pin: x.x
  gsl:
    max_pin: x.x
  numpy:
    max_pin: x.x
  numpyext:
    max_pin: x.x
  bpext:
    max_pin: x.x
  histogram:
    max_pin: x.x
  drchops:
    max_pin: x.x
