package:
  name: mcvine-core
  version: "1.3.2"

source:
  git_rev: v1.3.2
  git_url: https://github.com/mcvine/mcvine.git

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake
  host:
    - python
    - pyyaml
    - numpy                    {{ numpy }}
    - psutil
    - h5py
    - mpi4py
    - gsl                      {{ gsl }}
    - boost                    {{ boost }}
    - pyre
    - danse.ins.dsm
    - danse.ins.numpyext       {{ numpyext }}
    - danse.ins.bpext          {{ bpext }}
    - histogram                {{ histogram }}
    - diffpy.Structure
    - periodictable
    - drchops                  {{ drchops }}
    - mcvine-resources

  run:
    - python
    - pyyaml
    - numpy
    - psutil
    - h5py
    - mpi4py
    - gsl
    - boost
    - pyre
    - danse.ins.dsm
    - danse.ins.numpyext
    - danse.ins.bpext
    - histogram
    - diffpy.Structure
    - periodictable
    - drchops
    - mcvine-resources
    - phonopy
    - cmake
    - scipy
    - matplotlib

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - mcvine
  

about:
  home: 
  license:
  license_file:
