package:
  name: mcvine-core
  version: "1.5.1"

source:
  git_rev: v1.5.1
  git_url: https://github.com/mcvine/mcvine.git

requirements:
  build:
    - {{ compiler('cxx') }}    7                # [linux]
    - cmake
  host:
    - python                   {{ python }}
    - pyyaml
    - numpy                    {{ numpy }}
    - psutil
    - h5py
    - mpi4py
    - gsl                      {{ gsl }}
    - boost                    
    - mcpl
    - pyre
    - danse.ins.dsm
    - danse.ins.numpyext       {{ numpyext }}
    - danse.ins.bpext          {{ bpext }}
    - histogram                {{ histogram }}
    - diffpy.Structure         {{ structure }}
    - periodictable
    - mcvine-resources

  run:
    - {{ compiler('cxx') }}    7                # [linux]
    - cmake
    - python
    - pyyaml
    - numpy
    - psutil
    - h5py
    - mpi4py
    - gsl
    - boost
    - mcpl
    - pyre
    - danse.ins.dsm
    - danse.ins.numpyext
    - danse.ins.bpext
    - histogram
    - diffpy.Structure         {{ structure }}
    - periodictable
    - mcvine-resources
    - phonopy
    - scipy
    - matplotlib

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - mcvine

about:
  home:
  license:
  license_file:
