package:
  name: histogram
  version: "0.3.9"

source:
  git_rev: v0.3.9
  git_url: https://github.com/danse-inelastic/histogram.git

requirements:
  build:
    - {{ compiler('cxx') }}    7 # [linux]
    - cmake
  host:
    - python
    - numpy           {{ numpy }}
    - journal
  run:
    - python
    - numpy
    - danse.ins
    - journal
    - pyre
    - h5py

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - histogram
  

about:
  home: 
  license:
  license_file:
