package:
  name: histogram
  version: "0.3.2unstable"

source:
  git_rev: master
  git_url: https://github.com/danse-inelastic/histogram.git

requirements:
  build:
    - python
    - numpy x.x
    - journal
    - cmake

  run:
    - python
    - numpy x.x
    - danse.ins
    - journal
    - pyre
    - h5py

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - histogram
  

about:
  home: 
  license:
  license_file:
