package:
  name: mcvine.ui
  version: "0.0.1a6"

source:
  git_rev: v0.0.1a6
  git_url: https://github.com/mcvine/ui.git

requirements:
  build:
    - python
    - cmake

  run:
    - python
    - numpy
    - ipywe
    - mcvine.workflow >=0.1.0a6

build:

test:
  imports:
    - mcvine.ui

about:
  home: 
  license:
  license_file:
