package:
  name: mcvine.ui
  version: "0.0.1a8"

source:
  git_rev: v0.0.1a8
  git_url: https://github.com/mcvine/ui.git

requirements:
  build:
    - python
    - cmake

  run:
    - python
    - numpy
    - ipywe
    - mcvine-core >=1.3.2a6
    - mcvine.workflow >=0.1.0a8

build:

test:
  imports:
    - mcvine.ui

about:
  home: 
  license:
  license_file:
