package:
  name: mcvine.ui
  version: "0.0.3"

source:
  #no change in the source code, we point directly to a specific commit (head of master - v0.0.2)
  git_rev: 8bb1ff2fb9813125698317346437166ca8fc4d88
  git_url: https://github.com/mcvine/ui.git

requirements:
  build:
    - python
    - cmake

  run:
    - python >=3.7
    - numpy
    - notebook<7.0.0
    - ipywe==0.1.3a1
    - mcvine-core >=1.4.1
    - mcvine.workflow >=0.1.2

build:
  noarch: python

test:
  imports:
    - mcvine.ui

about:
  home: 
  license:
  license_file:
