package:
  name: mcvine.ui
  version: "0.0.2"

source:
  git_rev: v0.0.2
  git_url: https://github.com/mcvine/ui.git

requirements:
  build:
    - python
    - cmake

  run:
    - python >=3.7
    - numpy
    - notebook<7.0.0
    - ipywe==0.1.3a1
    - mcvine-core >=1.4.1
    - mcvine.workflow >=0.1.2

build:
  noarch: python

test:
  imports:
    - mcvine.ui

about:
  home: 
  license:
  license_file:
