package:
  name: drchops
  version: "2.0unstable"

source:
  git_rev: 2-alpha
  git_url: https://github.com/danse-inelastic/DrChops.git

requirements:
  build:
    - python
    - numpy x.x
    - danse.ins
    - journal
    - histogram
    - cmake

  run:
    - python
    - numpy x.x
    - danse.ins
    - journal
    - histogram
    - pyre

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - drchops
  

about:
  home: 
  license:
  license_file:
