package:
  name: drchops
  version: "2.0alpha"

source:
  git_rev: v2.0alpha
  git_url: https://github.com/danse-inelastic/DrChops.git

requirements:
  build:
    - numpy
    - danse.ins
    - journal
    - histogram
    - cmake

  run:
    - numpy
    - danse.ins
    - journal
    - histogram
    - pyre

test:
  imports:
    - drchops
  

about:
  home: 
  license:
  license_file:
