package:
  name: drchops
  version: "2.0.1"

source:
  git_rev: v2.0.1
  git_url: https://github.com/danse-inelastic/DrChops.git

requirements:
  build:
    - python
    - numpy        {{ numpy }}
    - danse.ins
    - journal
    - histogram
    - cmake

  run:
    - python
    - numpy
    - danse.ins
    - journal
    - histogram
    - pyre

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - drchops
  

about:
  home: 
  license:
  license_file:
