package:
  name: drchops
  version: "2.0.3"

source:
  git_rev: v2.0.3
  git_url: https://github.com/danse-inelastic/DrChops.git

requirements:
  build:
    - {{ compiler('cxx') }}        7 # [linux]
    - cmake
  host:
    - python
    - numpy        {{ numpy }}
    - danse.ins
    - journal
    - histogram    {{ histogram }}
  run:
    - python
    - numpy
    - danse.ins
    - journal
    - histogram
    - pyre

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - drchops
  

about:
  home: 
  license:
  license_file:
