package:
  name: mcvine
  version: "1.4.0"

requirements:
  run:
    - mcvine-core               >=1.4.0
    - mcvine.instruments
    - mcvine.workflow
    - mcvine.phonon
    - mantid-framework          4.0.0

build:
  noarch: python

about:
  home: 
  license: 
  license_file:
