package:
  name: mcvine
  version: "1.3.2unstable"

requirements:
  run:
    - mcvine-core
    - mcvine.instruments
    - mcvine.workflow
    - mcvine.phonon
    - mantid-framework 3.10

build:

about:
  home: 
  license: 
  license_file:
