package:
  name: mcvine
  version: "1.1"

source:
  git_rev: master
  git_url: https://github.com/mcvine/mcvine.git

requirements:
  build:
    - python
    - pyyaml
    - numpy
    - psutil
    - h5py
    - mpi4py
    - gsl
    - boost
    - pyre
    - danse.ins.dsm
    - danse.ins.numpyext
    - danse.ins.bpext
    - histogram
    - danse.ins.matter
    - drchops
    - mcvine-resources
    - cmake

  run:
    - python
    - pyyaml
    - numpy
    - psutil
    - h5py
    - mpi4py
    - gsl
    - boost
    - pyre
    - danse.ins.dsm
    - danse.ins.numpyext
    - danse.ins.bpext
    - histogram
    - danse.ins.matter
    - drchops
    - mcvine-resources

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - mcvine
  

about:
  home: 
  license:
  license_file:
