package:
  name: mcvine
  version: "1.4.5"

requirements:
  run:
    - mcvine-core               >=1.4.5
    - mcvine.instruments
    - mcvine.workflow
    - mcvine.phonon
    - mantid-framework          6

build:
  noarch: python
  string:

about:
  home: 
  license: 
  license_file:
