package:
  name: mcvine
  version: "1.3.4"

requirements:
  run:
    - mcvine-core      1.3.4
    - mcvine.instruments
    - mcvine.workflow
    - mcvine.phonon
    - mantid-framework >=3.13

build:

about:
  home: 
  license: 
  license_file:
