package:
  name: mcvine
  version: "1.4.5.2"

requirements:
  run:
    - mcvine-core               >=1.4.5
    - mcvine.instruments
    - mcvine.workflow
    - mcvine.phonon
    - mantid                    >=6.4

build:
  noarch: python
  string:

about:
  home: 
  license: 
  license_file:
