package:
  name: mcvine
  version: "1.4.7"

requirements:
  run:
    - mcvine-core               >=1.5.2
    - mcvine.instruments
    - mcvine.workflow
    - mcvine.phonon
    - mantid                    >=6.11

build:
  noarch: python
  string:

about:
  home: 
  license: 
  license_file:
