package:
  name: mantid2mcvine
  version: "0.1.4.2"

source:
  git_rev: v0.1.4
  git_url: https://github.com/mcvine/mantid2mcvine.git

requirements:
  host:
    - python

  run:
    - python                >=3.10
    - mcvine-core           >=1.4.5
    - mantid                >=6.4

build:
  noarch: python
  string:
  script_env:

test:
  imports:
    - mantid2mcvine

about:
  home: 
  license:
  license_file:
