package:
  name: mantid2mcvine
  version: "0.1.3"

source:
  git_rev: v0.1.3
  git_url: https://github.com/mcvine/mantid2mcvine.git

requirements:
  host:
    - python

  run:
    - python
    - mcvine-core           >=1.4.1
    - mantid-framework      5

build:
  noarch: python
  string:
  script_env:

test:
  imports:
    - mantid2mcvine

about:
  home: 
  license:
  license_file:
