package:
  name: mantid2mcvine
  version: "0.1.1"

source:
  git_rev: v0.1.1
  git_url: https://github.com/mcvine/mantid2mcvine.git

requirements:
  host:
    - python

  run:
    - python
    - mcvine-core           1.3.5
    - mantid-framework      4.0.0

build:
  noarch: python
  script_env:

test:
  imports:
    - mantid2mcvine

about:
  home: 
  license:
  license_file:
