package:
  name: mantid2mcvine
  version: "0.1.0a3"

source:
  git_rev: v0.1.0a3
  git_url: https://github.com/mcvine/mantid2mcvine.git

requirements:
  build:
    - python

  run:
    - python
    - mcvine-core
    - mantid-framework

build:

test:
  imports:
#    - mantid2mcvine

about:
  home: 
  license:
  license_file:
