package:
  name: pyre
  version: "0.8.3"

source:
  git_rev: v0.8.3
  git_url: https://github.com/danse-inelastic/pyre.git

requirements:
  build:
    - {{ compiler('cxx') }}       7  # [linux]
    - cmake

  host:
    - python

  run:
    - python
    - future
    - danse.ins
    - journal

build:
  script_env:

test:
  imports:
    - pyre
  

about:
  home: 
  license:
  license_file:
