package:
  name: pyre
  version: "0.8"

source:
  git_rev: v0.8
  git_url: https://github.com/danse-inelastic/pyre.git

requirements:
  build:
    - python
    - cmake

  run:
    - python
    - danse.ins
    - journal

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - pyre
  

about:
  home: 
  license:
  license_file:
