package:
  name: mcvine.phonon
  version: "dev"

source:
  git_rev: master
  git_url: https://github.com/mcvine/phonon.git

requirements:
  build:
    - python
    - cmake

  run:
    - python
    - mcvine

build:

test:
  imports:
    - mcvine.phonon  

about:
  home: 
  license:
  license_file:
