package:
  name: mcvine.phonon
  version: "0.1.0a5"

source:
  git_rev: v0.1.0a5
  git_url: https://github.com/mcvine/phonon.git

requirements:
  build:
    - python
    - cmake

  run:
    - python
    - mcvine-core >=1.3.2a6

build:

test:
  imports:
    - mcvine.phonon  

about:
  home: 
  license:
  license_file:
