package:
  name: mcvine.phonon
  version: "0.1.1"

source:
  git_rev: v0.1.1
  git_url: https://github.com/mcvine/phonon.git

requirements:
  build:
    - {{ compiler('cxx') }}    7                # [linux]
    - cmake

  host:
    - python

  run:
    - python
    - mcvine-core >=1.4

build:
  noarch: python

test:
  imports:
    - mcvine.phonon  

about:
  home: 
  license:
  license_file:
