{% set version = "6.1.0" %}
{% set git_rev = "v6.1.0" %}

package:
  name: mantid-framework
  version: {{ version }}

source:
  git_rev: {{ git_rev }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
    - _openmp_mutex {{ _openmp_mutex }} [linux64]
    - boost {{ boost }} 
    - cmake
    - eigen
    - gsl
    - gxx_linux-64 7.3.* [linux64]
    - h5py
    - hdf4
    - hdf5
    - jsoncpp
    - librdkafka
    - muparser
    - nexus
    - ninja
    - numpy {{ numpy }}
    - openblas
    - openssl
    - pkg-config
    - poco {{ poco }}
    - python {{ python }}
    - tbb-devel {{ tbb }}
    - pre-commit

  run:
    - _openmp_mutex {{ _openmp_mutex }} [linux64]
    - boost {{ boost }}
    - h5py
    - librdkafka
    - nexus
    - numpy
    - openblas
    - poco {{ poco }}
    - python
    - python-dateutil
    - pyyaml
    - scipy
    - six
    - tbb {{ tbb }}
    - gsl
    - jsoncpp
    - muparser
    - mkl

build:

about:
  home:
  license:
  license_file:
