package:
  name: mcvine-resources
  version: "1.0.5"

source:
  git_rev: v1.0.5
  git_url: https://github.com/mcvine/resources.git

requirements:
  build:
    - cmake
    - python

  run:
    - danse.ins

build:
  noarch: python
  script_env:
    - CC
    - CXX

test:
  imports:
    - danse.ins
  

about:
  home: 
  license:
  license_file:
