python:
#  - 2.7
#  - 3.7
  - 3.8
numpy:
#  - 1.16.0
#  - 1.19.0
  - 1.19.0
boost:
#  - 1.69
#  - 1.73
  - 1.73

zip_keys:
  - python
  - numpy
  - boost

pin_run_as_build:
  numpy:
    max_pin: x.x
  boost:
    max_pin: x.x
