package:
  name: danse.ins.bpext
  version: "0.1.1unstable"

source:
  git_rev: master
  git_url: https://github.com/danse-inelastic/bpext.git

requirements:
  build:
    - python
    - boost 1.61.*
    - cmake

  run:
    - python
    - boost 1.61.*
    - danse.ins

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - danse
    - danse.ins
    - danse.ins.bpext
  

about:
  home: 
  license:
  license_file:
