package:
  name: danse.ins.bpext
  version: "0.1.2"

source:
  git_rev: v0.1.2
  git_url: https://github.com/danse-inelastic/bpext.git

requirements:
  build:
    - python
    - boost {{ boost }}
    - cmake

  run:
    - python
    - boost
    - danse.ins

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - danse
    - danse.ins
    - danse.ins.bpext
  

about:
  home: 
  license:
  license_file:
