package:
  name: danse.ins.bpext
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/danse-inelastic/bpext.git

requirements:
  build:
    - python
    - boost
    - cmake

  run:
    - python
    - boost
    - danse.ins

test:
  imports:
    - danse.ins.bpext
  

about:
  home: 
  license:
  license_file:
