package:
  name: mcvine.instruments
  version: "0.1.0a6"

source:
  git_rev: v0.1.0a6
  git_url: https://github.com/mcvine/instruments.git

requirements:
  build:
    - python
    - cmake
    - mcvine-core

  run:
    - python
    - mcvine-resources >=1.0.3
    - mcvine-core >=1.3.2a7
    - mantid2mcvine

build:

test:
  imports:
    - mcvine.instruments

about:
  home: 
  license:
  license_file:
