package:
  name: mcvine.instruments
  version: "0.1.0a3"

source:
  git_rev: v0.1.0a3
  git_url: https://github.com/mcvine/instruments.git

requirements:
  build:
    - python
    - cmake
    - mcvine-core

  run:
    - python
    - mcvine-core
    - mantid2mcvine

build:

test:
  imports:
    - mcvine.instruments

about:
  home: 
  license:
  license_file:
