package:
  name: mcvine.instruments
  version: "0.1.1"

source:
  git_rev: v0.1.1
  git_url: https://github.com/mcvine/instruments.git

requirements:
  build:
    - {{ compiler('cxx') }}    7                # [linux]
    - cmake

  host:
    - python

  run:
    - python
    - mcvine-resources >=1.0.5
    - mcvine-core >=1.4
    - mantid2mcvine >=0.1.1

build:
  noarch: python

test:
  imports:
    - mcvine.instruments

about:
  home: 
  license:
  license_file:
