package:
  name: danse.ins.numpyext
  version: "0.1.1unstable"

source:
  git_rev: master
  git_url: https://github.com/danse-inelastic/numpyext.git

requirements:
  build:
    - python
    - numpy x.x
    - cmake

  run:
    - python
    - numpy x.x
    - danse.ins

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - danse.ins.numpyext
  

about:
  home: 
  license:
  license_file:
