package:
  name: danse.ins.numpyext
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/danse-inelastic/numpyext.git

requirements:
  build:
    - python
    - numpy
    - cmake

  run:
    - python
    - numpy
    - danse.ins

build:
  script_env:
    - CC
    - CXX

test:
  imports:
    - danse.ins.numpyext
  

about:
  home: 
  license:
  license_file:
