package:
  name: danse.ins.numpyext
  version: "0.1.3"

source:
  git_rev: v0.1.3
  git_url: https://github.com/danse-inelastic/numpyext.git

requirements:
  build:
    - {{ compiler('cxx') }}       7  # [linux]
    - cmake

  host:
    - python
    - numpy     {{ numpy }}

  run:
    - python
    - numpy
    - danse.ins

build:
  script_env:
    - CC
    - CXX
  string:

test:
  imports:
    - danse.ins.numpyext
  

about:
  home: 
  license:
  license_file:
