{% set build_number = "1" %}

package:
  name: danse.ins.numpyext
  version: "0.1.4rc1"

source:
  git_rev: v0.1.4rc1
  git_url: https://github.com/danse-inelastic/numpyext.git

requirements:
  build:
    - {{ compiler('cxx') }}       7  # [linux]
    - cmake

  host:
    - python
    - numpy     {{ numpy }}

  run:
    - python     {{ python }}
    - numpy     {{ numpy }}
    - danse.ins

build:
  script_env:
    - CC
    - CXX
  number: {{ build_number }}
  
test:
  imports:
    - danse.ins.numpyext
  

about:
  home: 
  license:
  license_file:
