name: Deploy

env: {"CI_NAME": "github-actions"}

on:
  workflow_dispatch:

jobs:
  danse-bpext-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build danse/bpext


  danse-ins-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build danse/danse.ins

  danse-dsm-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build danse/dsm
  danse-journal-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build danse/journal
  danse-numpyext-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build danse/numpyext
  danse-pyre-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build danse/pyre
  mantid2mcvine-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build mantid2mcvine
  mcvine-core-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build mcvine-core

  mcvine-resources-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build mcvine-resources
  mcvine-instruments-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build mcvine.instruments
  mcvine-phonon-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build mcvine.phonon
  mcvine-ui-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build mcvine.ui
  mcvine-workflow-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build mcvine.workflow
  mcvine-pkg:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: Micromamba info
        shell: bash -l {0}
        run: micromamba info
      - name: build_package
        shell: bash -l {0}
        run: |
            conda build mcvine






