name: McvineDeploy

env: {"CI_NAME": "github-actions"}

on:
  workflow_dispatch:
    inputs:
      run_mantid2mcvine-pkg:
        description: 'Deploy mantid2mcvine?'
        required: false
        type: boolean
        default: false        
      run_mcvine-core-pkg:
        description: 'Deploy mcvine-core?'
        required: false
        type: boolean
        default: false        
      run_mcvine-resources-pkg:
        description: 'Deploy mcvine-resources?'
        required: false
        type: boolean
        default: false        
      run_mcvine-instruments-pkg:
        description: 'Deploy mcvine.instruments?'
        required: false
        type: boolean
        default: false        
      run_mcvine-phonon-pkg:
        description: 'Deploy mcvine.phonon?'
        required: false
        type: boolean
        default: false        
      run_mcvine-ui-pkg:
        description: 'Deploy mcvine.ui?'
        required: false
        type: boolean
        default: false        
      run_mcvine-workflow-pkg:
        description: 'Deploy mcvine.workflow?'
        required: false
        type: boolean
        default: false        
      run_mcvine-pkg:
        description: 'Deploy mcvine?'
        required: false
        type: boolean
        default: false        

jobs:
  main-branch:
    runs-on: ubuntu-latest
    outputs:
      is_master: ${{ steps.branch_info.outputs.is_master }}
    steps:
      - name: Get branch info
        id: branch_info
        shell: bash -l {0}
        run: |
          echo "is_master=${{ github.ref != 'refs/heads/master'}}" >> $GITHUB_OUTPUT
      - name: Branch Access
        run: |
          if [ "${{ steps.branch_info.outputs.is_master }}" == "true" ]; then
            echo "Master Branch found!"
          else
            echo "Deploy workflow runs only on the master branch!"
            exit 1
          fi  
        
  check-permission:
    needs: main-branch
    runs-on: ubuntu-latest
    outputs:
      is_permitted: ${{ steps.permission.outputs.is_permitted }}
    steps:
      - name: Get user mcvine-dev membership
        id: get_permission
        uses: tspascoal/get-user-teams-membership@v2
        with:
          GITHUB_TOKEN: ${{ secrets.TEAM_TOKEN }}
          username: ${{ github.actor }}
          team: deploy
          organization: 'mcvine'
      - name: Set user membership status
        id: permission
        shell: bash -l {0}
        run: |
          echo "is_permitted=${{ steps.get_permission.outputs.isTeamMember == 'true'}}" >> $GITHUB_OUTPUT
      - name: User Access
        run: |
          if [ "${{ steps.permission.outputs.is_permitted }}" == "true" ]; then
            echo "Access Granted for Deploy!"
          else
            echo "Access Denied!"
            exit 1
          fi  
        
  mantid2mcvine-pkg:
    needs: check-permission
    runs-on: ubuntu-latest
    if: ${{ needs.check-permission.outputs.is_permitted == 'true' && github.event.inputs.run_mantid2mcvine-pkg == 'true' }} 
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: build_package
        shell: bash -l {0}
        run: conda build mantid2mcvine --output-folder .
      - name: Upload package to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          CONDA_USER="mcvine"
          CONDA_LABEL="main"
          if [[ "noarch/mantid2mcvine-*" =~ ([0-9]+rc[0-9]+) ]]; then
            CONDA_LABEL="rc"
          fi
          echo noarch/mantid2mcvine-* pushing with label $CONDA_LABEL
          # anaconda upload --label CONDA_LABEL --user $CONDA_USER

  mcvine-core-pkg:
    needs: check-permission
    runs-on: ubuntu-latest
    if: ${{ needs.check-permission.outputs.is_permitted == 'true' && github.event.inputs.run_mcvine-core-pkg == 'true' }} 
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: build_package
        shell: bash -l {0}
        run: conda build mcvine-core --output-folder .
      - name: Upload package to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          CONDA_USER="mcvine"
          CONDA_LABEL="main"
          if [[ "linux-64/mcvine-core-*" =~ ([0-9]+rc[0-9]+) ]]; then
            CONDA_LABEL="rc"
          fi
          echo linux-64/mcvine-core-* pushing with label $CONDA_LABEL
          # anaconda upload --label CONDA_LABEL --user $CONDA_USER

  mcvine-resources-pkg:
    needs: check-permission
    runs-on: ubuntu-latest
    if: ${{ needs.check-permission.outputs.is_permitted == 'true' && github.event.inputs.run_mcvine-resources-pkg == 'true' }} 
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: build_package
        shell: bash -l {0}
        run: conda build mcvine-resources --output-folder .
      - name: Upload package to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          CONDA_USER="mcvine"
          CONDA_LABEL="main"
          if [[ "noarch/mcvine-resources-*" =~ ([0-9]+rc[0-9]+) ]]; then
            CONDA_LABEL="rc"
          fi
          echo noarch/mcvine-resources-* pushing with label $CONDA_LABEL
          # anaconda upload --label CONDA_LABEL --user $CONDA_USER
      
  mcvine-instruments-pkg:
    needs: check-permission
    runs-on: ubuntu-latest
    if: ${{ needs.check-permission.outputs.is_permitted == 'true' && github.event.inputs.run_mcvine-instruments-pkg == 'true' }} 
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: build_package
        shell: bash -l {0}
        run: conda build mcvine.instruments --output-folder .
      - name: Upload package to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          CONDA_USER="mcvine"
          CONDA_LABEL="main"
          if [[ "noarch/mcvine.instruments-*" =~ ([0-9]+rc[0-9]+) ]]; then
            CONDA_LABEL="rc"
          fi
          echo noarch/mcvine.instruments-* pushing with label $CONDA_LABEL
          # anaconda upload --label CONDA_LABEL --user $CONDA_USER

  mcvine-phonon-pkg:
    needs: check-permission
    runs-on: ubuntu-latest
    if: ${{ needs.check-permission.outputs.is_permitted == 'true' && github.event.inputs.run_mcvine-phonon-pkg == 'true' }} 
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: build_package
        shell: bash -l {0}
        run: conda build mcvine.phonon --output-folder .
      - name: Upload package to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          CONDA_USER="mcvine"
          CONDA_LABEL="main"
          if [[ "noarch/mcvine.phonon-*" =~ ([0-9]+rc[0-9]+) ]]; then
            CONDA_LABEL="rc"
          fi 
          echo noarch/mcvine.phonon-* pushing with label $CONDA_LABEL
          # anaconda upload --label CONDA_LABEL --user $CONDA_USER

  mcvine-ui-pkg:
    needs: check-permission
    runs-on: ubuntu-latest
    if: ${{ needs.check-permission.outputs.is_permitted == 'true' && github.event.inputs.run_mcvine-ui-pkg == 'true' }} 
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: build_package
        shell: bash -l {0}
        run: conda build mcvine.ui --output-folder .
      - name: Upload package to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          CONDA_USER="mcvine"
          CONDA_LABEL="main"
          if [[ "noarch/mcvine.ui-*" =~ ([0-9]+rc[0-9]+) ]]; then
            CONDA_LABEL="rc"
          fi 
          echo noarch/mcvine.ui-* pushing with label $CONDA_LABEL
          # anaconda upload --label CONDA_LABEL --user $CONDA_USER

  mcvine-workflow-pkg:
    needs: check-permission
    runs-on: ubuntu-latest
    if: ${{ needs.check-permission.outputs.is_permitted == 'true' && github.event.inputs.run_mcvine-workflow-pkg == 'true' }} 
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: build_package
        shell: bash -l {0}
        run: conda build mcvine.workflow --output-folder .
      - name: Upload package to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          CONDA_USER="mcvine"
          CONDA_LABEL="main"
          if [[ "noarch/mcvine.workflow-*" =~ ([0-9]+rc[0-9]+) ]]; then
            CONDA_LABEL="rc"
          fi 
          echo noarch/mcvine.workflow-* pushing with label $CONDA_LABEL
          # anaconda upload --label CONDA_LABEL --user $CONDA_USER

  mcvine-pkg:
    needs: check-permission
    runs-on: ubuntu-latest
    if: ${{ needs.check-permission.outputs.is_permitted == 'true' && github.event.inputs.run_mcvine-pkg == 'true' }} 
    steps:
      - uses: actions/checkout@v4
      - name: Micromamba    
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: shared_environment.yml
          condarc: |
            channels:
            - neutrons
            - mantid
            - mcvine
            - mcvine/label/rc
            - conda-forge
      - name: build_package
        shell: bash -l {0}
        run: conda build mcvine --output-folder .
      - name: Upload package to anaconda
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          CONDA_USER="mcvine"
          CONDA_LABEL="main"
          pkg=`ls noarch/mcvine-[0-9]*`
          if [[ $pkg =~ ([0-9]+rc[0-9]+) ]]; then
            CONDA_LABEL="rc"
          fi  
          echo pkg pushing with label $CONDA_LABEL
          # anaconda upload --label CONDA_LABEL --user $CONDA_USER
